### PR TITLE
Mark the application as EOL

### PR DESCRIPTION
**Pull request by ghost**
This application is no longer maintained because the Eclipse Foundation no longer creates standalone RCP apps.

Source: https://github.com/flathub/org.eclipse.Javascript/pull/19#issuecomment-2155864966

### CODE REVIEW

**Comment by ghost** [comment]
@bbhtt org.eclipse.Javascript marked as EOL.

Source: https://github.com/flathub/org.eclipse.Javascript/pull/19#issuecomment-2169148692

**Comment by akurtakov** [comment]
I have adjusted the message to be more detailed as it's not EF that makes decisions whether projects ship RCP app or not.

**Comment by bbhtt** [comment]
cc @akurtakov Merging this will retire the app.


(I'll merge in a few weeks if no one responds, since the maintainer already wished it to be retired)

**Comment by clue** [comment]
The suggested changes make sense to me. Additionally, perhaps we could point people currently relying on this towards the up-to-date https://github.com/flathub/org.eclipse.Java?

It's my understanding that the soon-to-be-deprecated [Eclipse IDE for Web and JavaScript Developers](https://flathub.org/apps/org.eclipse.Javascript) is pretty much just [Eclipse IDE for Java Developers](https://flathub.org/apps/org.eclipse.Java) plus the [Eclipse Wild Web Developer](https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper) extension, so most users should have an easy upgrade path. Not sure if the `end-of-life` field should carry this information or if there's another piece of meta data that could be used for the Flathub listing at least?

**Comment by bbhtt** [comment]
Yea you can add "Please use com.foo.bar" to the message.

**Comment by akurtakov** [comment]
> It's my understanding that the soon-to-be-deprecated [Eclipse IDE for Web and JavaScript Developers](https://flathub.org/apps/org.eclipse.Javascript) is pretty much just [Eclipse IDE for Java Developers](https://flathub.org/apps/org.eclipse.Java) plus the [Eclipse Wild Web Developer](https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper) extension

The content of RCP product built by wildwebdeveloper didn't include the java tooling so roughly org.eclipse.Java = Eclipse Platform + Eclipse JDT + Eclipse PDE and org.eclipse.Javascript = Eclipse Platform + Eclipse WildWebDeveloper . People can  install Eclipse WildWebdeveloper plugin on top of any Eclipse Platform installation and the one I know available at flathub is org.eclipse.Java.

**Pull request merged**
