### PR TITLE
Update Eclipse Javascript runtime to 46

### PR DESCRIPTION
**Pull request by ghost**
- Update Eclipse Javascript runtime to 46 since runtime version 44 has reached end-of-life.

### CODE REVIEW

**Comment by ghost** [comment]
@akurtakov I've updated Eclipse Javascript IDE runtime to version 46 since runtime version 44 has reached end-of-life. Could you test it?

**Comment by akurtakov** [comment]
JS LS is not starting proper (java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/node" (in directory "/app/eclipse/plugins/org.eclipse.wildwebdeveloper_1.1.0.202306291300"): No such file or directory). Unfortunately, I haven't tested the main version in years whether it works proper. 
As https://download.eclipse.org/wildwebdeveloper/releases/1.3.6/ no longer creates standalone RCP app I think it's best to actually retire this app from flathub.

**Comment by akurtakov** [comment]
Do you know how to do that?

**Comment by ghost** [comment]
I think you can open an issue here: https://github.com/flathub/flathub/issues

**Comment by ghost** [comment]
> JS LS is not starting proper (java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/node" (in directory "/app/eclipse/plugins/org.eclipse.wildwebdeveloper_1.1.0.202306291300"): No such file or directory). Unfortunately, I haven't tested the main version in years whether it works proper. As https://download.eclipse.org/wildwebdeveloper/releases/1.3.6/ no longer creates standalone RCP app I think it's best to actually retire this app from flathub.

@mbooth101 What you think about the suggestion?

**Comment by bbhtt** [comment]
> I think it's best to actually retire this app from flathub.

https://docs.flathub.org/docs/for-app-authors/maintenance#end-of-life

**Pull request closed without merging**
